# https://github.com/rundeck/docker-zoo/tree/master
include:
  - ../core/compose.yml
services:
  rundeck:
    image: rundeck/rundeck:5.3.0
    networks:
      - caddy
    labels:
      caddy: dagu.eraldy.com
      caddy.reverse_proxy: "{{upstreams 4440}}"
    volumes:
      - rundeck_data:/home/rundeck/server/data
volumes:
  rundeck_data:

