

# Global variable for all domain
bytle_name: 'bytle'
bytle_base_dir: '{{ www_root_dir }}/{{ bytle_name }}'
bytle_base_log_dir: '/var/log/nginx/{{ bytle_name }}'

# bytle.net domain
bytle_fqdn: '{{ bytle_name }}.net'
bytle_root_dir: '{{ bytle_base_dir}}/{{ bytle_fqdn }}'
bytle_log_dir: '{{ bytle_base_log_dir }}/{{ bytle_fqdn }}'

# farmer.bytle.net domain
bytle_farmer_fqdn: 'farmer.{{ bytle_fqdn }}'
bytle_farmer_root_dir: '{{ bytle_base_dir}}/{{ bytle_farmer_fqdn }}'
bytle_farmer_log_dir: '{{ bytle_base_log_dir }}/{{ bytle_farmer_fqdn }}'

# onepager.bytle.net domain
bytle_onepager_fqdn: 'onepager.{{ bytle_fqdn }}'
bytle_onepager_root_dir: '{{ bytle_base_dir}}/{{ bytle_farmer_fqdn }}'
bytle_onepager_log_dir: '{{ bytle_base_log_dir }}/{{ bytle_onepager_fqdn }}'

