

combo_name: 'combostrap'
combo_base_dir: '{{ www_root_dir }}/{{ combo_name }}'
combo_base_log_dir: '/var/log/nginx/{{ combo_name }}'

combo_fqdn: '{{ combo_name }}.com'
# Combostrap is an animal of bytle
combo_root_dir: '{{ bytle_base_dir}}/{{ bytle_farmer_fqdn }}'
combo_log_dir: '{{ combo_base_log_dir }}/{{ combo_fqdn }}'

combo_demo_fqdn: 'demo.{{ combo_name }}.com'
combo_demo_log_dir: '{{ combo_base_log_dir }}/{{ combo_demo_fqdn }}'

