# Global
gnico_name: 'gerardnico'
gnico_base_dir: '{{ www_root_dir }}/{{ gnico_name }}'

# gerardnico.com (php)
gnico_fqdn: '{{ gnico_name }}.com'

## farmer
gnico_farmer_fqdn: 'farmer.{{ gnico_fqdn }}'
gnico_farmer_root_dir: '{{ gnico_base_dir }}/{{ gnico_farmer_fqdn }}'


gnico_nico_fqdn: 'nico.{{ gnico_fqdn }}'
gnico_rixt_fqdn: 'rixt.{{ gnico_fqdn }}'
