

# Global variable for all domain
bytle_name: 'bytle'
bytle_base_dir: '{{ www_root_dir }}/{{ bytle_name }}'

# bytle.net domain
bytle_fqdn: '{{ bytle_name }}.net'
bytle_root_dir: '{{ bytle_base_dir}}/{{ bytle_fqdn }}'

# farmer.bytle.net domain
bytle_farmer_fqdn: 'farmer.{{ bytle_fqdn }}'
bytle_farmer_root_dir: '{{ bytle_base_dir}}/{{ bytle_farmer_fqdn }}'

# animals
combo_fqdn: 'combostrap.com'
combo_wildcard_fqdn: '*.combostrap.com'
combo_demo_fqdn: 'demo.{{ combo_fqdn }}'
tabulify_fqdn: 'tabulify.com'
eraldy_fqdn: 'eraldy.com'
persso_fqdn: 'persso.com'

# farmer and animal list
nginx_dokuwiki_domains:
  - '{{ bytle_farmer_fqdn }}'
  - '{{ bytle_fqdn }}'
  - '{{ combo_fqdn }}'
  - '{{ combo_demo_fqdn }}'
  - '{{ tabulify_fqdn }}'
  - '{{ eraldy_fqdn }}'
  - '{{ persso_fqdn }}'
