
gnico_repository_pwd: '{{ vault_gnico_repository_pwd }}'

gnico_port: 8083
gnico_app: apignico

# The app has two different endpoint
gnico_fqdn: 'gerardnico.com'
gnico_fqdn_api: 'api.{{ gnico_fqdn }}'
gnico_fqdn_analytics: 'analytics.{{ gnico_fqdn }}'

