# Global
gnico_name: 'gerardnico'
gnico_base_dir: '{{ www_root_dir }}/{{ gnico_name }}'
gnico_base_log_dir: '/var/log/nginx/{{ gnico_name }}'

# gerardnico.com (php)
gnico_fqdn: '{{ gnico_name }}.com'
gnico_log_dir: '{{ gnico_base_log_dir }}/{{ gnico_fqdn }}'

## farmer
gnico_farmer_fqdn: 'farmer.{{ gnico_fqdn }}'
gnico_farmer_root_dir: '{{ gnico_base_dir }}/{{ gnico_farmer_fqdn }}'
gnico_farmer_log_dir: '{{ gnico_base_log_dir }}/{{ gnico_farmer_fqdn }}'

## nico.gnico.com
gnico_nico_fqdn: 'nico.{{ gnico_fqdn }}'
gnico_nico_root_dir: '{{ gnico_farmer_root_dir }}'
gnico_nico_log_dir: '{{ gnico_base_log_dir }}/{{ gnico_nico_fqdn }}'
