gogs_fqdn: gogs.bytle.net
gogs_mail_enabled: true

# The local user (gogs support only STARTLS)
gogs_mail_user: gnico-mail@bytle.net
gogs_mail_password: '{{ gnico_mail_password_vault }}'
gogs_mail_host: localhost:587
gogs_mail_from: gogs@bytle.net

gogs_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39393331323635623832663365656164346162346531346536383938643262363639383462363130
  3630323637373736633262343430366463353864626132620a353662333766366434326465366662
  61636366363833306361656665666661383736306262366239366561626334663832313364363833
  6239376634326666630a356239663532616131653266313834333439366137383834373136383064
  3462
gogs_ssh_port: "22"





