gogs_fqdn: gogs.bytle.net
gogs_mail_enabled: true
gogs_mail_user: postmaster@gerardnico.com
gogs_mail_from: gogs@bytle.net
gogs_mail_host: smtp.gerardnico.com:587
gogs_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39393331323635623832663365656164346162346531346536383938643262363639383462363130
  3630323637373736633262343430366463353864626132620a353662333766366434326465366662
  61636366363833306361656665666661383736306262366239366561626334663832313364363833
  6239376634326666630a356239663532616131653266313834333439366137383834373136383064
  3462
gogs_mail_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61396563643566333636383438393736336330303434393365656437613134313032393630363237
  6632393034633563333430386662383961633737383663310a383237643337316266363865373962
  38376437346261633464633731313163383430616232636261303332383866636233383437366235
  3433643961646338320a343630616236373936363131343535326366393832363736636631376461
  39613336643534336562643333613938343663323733363562393464316161646436
gogs_ssh_port: "{{ ssh_target_port }}"





