
# The nexus port will be available from this ip
nexus_white_ip_address:
  - 127.0.0.1

# To not conflict with other service
nexus_port: 8082

# For nginx
nexus_fqdn: 'nexus.bytle.net'
nexus_context_path: '/'
