

letsencrypt_email: nico@bytle.net

ovh_domains:
  - bytle.net
  - netdata.bytle.net
  - nexus.bytle.net
  - api.bytle.net

cloudflare_domains:
  - '{{ gnico_fqdn_api }}'
  - '{{ gnico_fqdn_analytics }}'


dns_ovh_consumer_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33333331363139343762323561646538313339333234666437633136386537393234626636646335
  3533666432353863396663323930333339313335373534640a386434663461633564333034613934
  34376131636433306362343231336239333465653633303435656361363231376238396231626130
  3937656436613864640a666232326331653032643430613933323063323932616565633133336565
  64383034636536646639643131326537346531333334323963383239383434613934333939313336
  3363333461373366363733303537393139386338303137656437

dns_ovh_application_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39353061373066666639353632643232646333373135333264343264343834326237333664336337
  3266353330363865353039333336343738643136346537610a616339303536353563333431323563
  32336362376332353430376231393534336434306366383037306632653230326439343334636165
  6235363735386563630a646538396539343634656237646261326432663136636639623936613661
  64303763393636363262316137643466353065666336386564383865373665303365

dns_ovh_application_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61356330626162356165376665313762333961646465356534313936363139653464383563316637
  3033633038363165633261343163386537396133633037390a626630396536306665316633386231
  38373266383035363836316466396533656536333035653731383562663334363163393862633965
  6362376438373139620a643461366631336635376166663764626533343662626133396165636539
  66366433346634353134346665373434663263383833383136323833346365373062393863663536
  3336373463373338303462623937373564356436333833313965

dns_cloudflare_email: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66353238393331613261333835363536613035356131323633303837313664616330663532633966
  3330663335373434633630303731363537616561646337660a326431343066383161613034663063
  37616331616439306431366162363566636661373863653364626337376234656431613737363836
  3866393436313533650a323536336361393133626236363239393861376135336137383630663764
  36653832383734656139653763626266393832623963363064356462326533373837

dns_cloudflare_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63323566366565323239613634356234353565323630666163376531326332363631646131326636
  3631643739353461363565633864356666356339386631640a323336353538613838353463653938
  38646637303439353234366336663839363561326666393731623261613538616634316331383838
  6437326565306335390a363830393665373266613565616635313434326233633134366237613134
  62646364303166636539623139373331396436626535343831623636313539343966333362633331
  6432663537666434633233386565663662663263623431316633


