

letsencrypt_email: nico@bytle.net

ovh_domains:
  - bytle.net
  - netdata.bytle.net
  - nexus.bytle.net
  - gogs.bytle.net
  - '{{ backend_fqdn_api }}'
  - '{{ backend_fqdn_analytics }}'
  - '{{ datacadamia_fqdn }}'
  - '{{ prometheus_node_exporter_fqdn }}'

cloudflare_domains:
  - '{{ gnico_fqdn }}'


dns_ovh_application_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32363265343730633332313366633031323234353036653236646633323964363938326363343665
  6531643063653537643763343837336639363538373933360a363631316533353563383237323462
  61333336653562373333613237646431396337636130666461386163393465303831636562323736
  3365656566363264320a656136303137393835623037323934343666333562303230656665666132
  32313466346535646433313961643435326262333339316363356362346238383032

dns_ovh_application_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61643661316338333266343236363934646434326464376637303638346364623932343866656261
  3938316336303330366662626161336531616130323938350a613439336531386561393934656633
  66383235633333383032303334363864356535313830343031666463376535363737333731313534
  3535393137373632640a656531663733396531353463326239623434396339333833313036373335
  38616637323234343965633063356466653835653063373561346430373532313636303761636261
  6465343763356235656264616231383435306362633062343134

dns_ovh_consumer_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62346536386539663439356236616337356631633032396232633865343934396335383463373833
  3537306461656437333731653437386564333835396533380a306462353531393738666430633665
  63376262376262633165323731356233326162663835643638656538373238326164326639333931
  3464353831663136390a653335656135383934653439316434666164336435646362626138303533
  35626664646131356364363435323432306230386436326437383536396134386139396436316262
  6662383230393737393431376530633739643534353934653962


dns_cloudflare_email: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66353238393331613261333835363536613035356131323633303837313664616330663532633966
  3330663335373434633630303731363537616561646337660a326431343066383161613034663063
  37616331616439306431366162363566636661373863653364626337376234656431613737363836
  3866393436313533650a323536336361393133626236363239393861376135336137383630663764
  36653832383734656139653763626266393832623963363064356462326533373837

dns_cloudflare_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63323566366565323239613634356234353565323630666163376531326332363631646131326636
  3631643739353461363565633864356666356339386631640a323336353538613838353463653938
  38646637303439353234366336663839363561326666393731623261613538616634316331383838
  6437326565306335390a363830393665373266613565616635313434326233633134366237613134
  62646364303166636539623139373331396436626535343831623636313539343966333362633331
  6432663537666434633233386565663662663263623431316633


