# User to connect
# It should be here and not in a role
# otherwise we can't connect when running an ad-hoc module with the ansible cli
ssh_user_name: 'nickeau'
ssh_user_password: '{{ ssh_user_password_vault }}' #  to avoid argument 1 must be string
ssh_user_password_vault:  !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32626436303536616163366133623338343563393932353734353766366362343261303737353834
  3434323335653936376461303062363234386664623432390a343539636164353361326165333735
  35386365326164663432663164626363613162623961623966343730663035336138386133663336
  6265383461333234340a356365643234366239366339373333393537336661633965326236386632
  36356539643939616635393234653834353466626466383135336631346364383731
