vault_root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38613863336265643965653332323638343563333961613633626665303138616461623261313434
  6465663739396437626636613036643663623763306335350a643930656538383766393534306365
  65383161376236623663393732306563346664376630303265353937336165346430306338613366
  3561626133383562380a373139393438663939333765346664633537653739613032336139653034
  6139
