vault_root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38613863336265643965653332323638343563333961613633626665303138616461623261313434
  6465663739396437626636613036643663623763306335350a643930656538383766393534306365
  65383161376236623663393732306563346664376630303265353937336165346430306338613366
  3561626133383562380a373139393438663939333765346664633537653739613032336139653034
  6139

vault_user_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32626436303536616163366133623338343563393932353734353766366362343261303737353834
  3434323335653936376461303062363234386664623432390a343539636164353361326165333735
  35386365326164663432663164626363613162623961623966343730663035336138386133663336
  6265383461333234340a356365643234366239366339373333393537336661633965326236386632
  36356539643939616635393234653834353466626466383135336631346364383731

vault_dns_ovh_application_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39353061373066666639353632643232646333373135333264343264343834326237333664336337
  3266353330363865353039333336343738643136346537610a616339303536353563333431323563
  32336362376332353430376231393534336434306366383037306632653230326439343334636165
  6235363735386563630a646538396539343634656237646261326432663136636639623936613661
  64303763393636363262316137643466353065666336386564383865373665303365

vault_dns_ovh_application_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61356330626162356165376665313762333961646465356534313936363139653464383563316637
  3033633038363165633261343163386537396133633037390a626630396536306665316633386231
  38373266383035363836316466396533656536333035653731383562663334363163393862633965
  6362376438373139620a643461366631336635376166663764626533343662626133396165636539
  66366433346634353134346665373434663263383833383136323833346365373062393863663536
  3336373463373338303462623937373564356436333833313965

vault_dns_ovh_consumer_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33333331363139343762323561646538313339333234666437633136386537393234626636646335
  3533666432353863396663323930333339313335373534640a386434663461633564333034613934
  34376131636433306362343231336239333465653633303435656361363231376238396231626130
  3937656436613864640a666232326331653032643430613933323063323932616565633133336565
  64383034636536646639643131326537346531333334323963383239383434613934333939313336
  3363333461373366363733303537393139386338303137656437

vault_gnico_fat_url_auth_pwd:
  !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32653434643132313862646362363964303334343935323732356235396530653832336435656561
  3366326336636466343430633030663262633033343436610a326330643039653430363931303431
  36383237303235386632636162376338393938356666333836633237303332636631666463353730
  6639333238303831660a393038393965336162316463353863636164613135303761396465316230
  61643166346665383037643438323464623135353730633333613336373430313365
