vault_root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38613863336265643965653332323638343563333961613633626665303138616461623261313434
  6465663739396437626636613036643663623763306335350a643930656538383766393534306365
  65383161376236623663393732306563346664376630303265353937336165346430306338613366
  3561626133383562380a373139393438663939333765346664633537653739613032336139653034
  6139

vault_user_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32626436303536616163366133623338343563393932353734353766366362343261303737353834
  3434323335653936376461303062363234386664623432390a343539636164353361326165333735
  35386365326164663432663164626363613162623961623966343730663035336138386133663336
  6265383461333234340a356365643234366239366339373333393537336661633965326236386632
  36356539643939616635393234653834353466626466383135336631346364383731


vault_gnico_repository_pwd: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65393232353038333034316235636362613563313861393865333030636234393730363434366639
  3339616537323362356538666331633038336630393832350a316138326331306138646131323739
  37313531643639393736353133386161323765376633343839613035393131386365653032393939
  3338383433646535360a646139363231306565613139613938393361316333306465343064383237
  31316531623431333836636338653463333636393863373231316166376238306138

# The user password that manage the website
vault_www_user_pwd: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37653862623031666463363162613335356336636231366665393962306234643064323030396339
  3066363762363638633462646361333134393134376232660a323830646161366537613261656530
  37346630323965646661396161376361323431323832366666363366613538383736646463316137
  6264666164616438350a653161396235333561386439376632303561303563386233346630626531
  6263
