
# The conf file
dkim_conf_path: /etc/opendkim.conf

# The key / domain mapping file
dkim_key_table_path: /etc/opendkim/KeyTable

# The location of the keys
dkim_keys_path: /etc/opendkim/keys

# The key selector (Hostname)
dkim_selector: '{{ ansible_hostname }}'

# The location of the key
dkim_key_path: '{{ dkim_keys_path }}/{{ dkim_selector }}.private'



# The path to the SigningTable
dkim_signing_table_path: /etc/opendkim/SigningTable

# The dns key is used in the DNS and other configuration file
dkim_dns_key: '{{ dkim_selector }}._domainkey.{{ dkim_domain }}'

# Created during the package installation
dkim_owner: opendkim
dkim_group: opendkim

dkim_socket_port: 8891

# The domain
dkim_domain: 'bytle.net'


# The private key
dkim_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62353764313063643231633930613935343431366437653064396635316238366234666265336338
  3163393665326166313464386364356432323838613430350a356635663266326439343936643233
  66656665386564623965393762643437666264663634393965353832633138303065373636656330
  3337363030326532350a353037353635616133666338653930386362336132613336383263616335
  35623362393830613261373264656562336266616430323232333031313233326131653030396136
  37363932393238353930626662633465313764643031613165343239666561366639333232383636
  38633964323234653836373064376464323834633562396633303234306366623437326636633930
  32303263666663343461626233303166653430633832613731626565636366313063313731393463
  31393735386630386635363661386535316662383264313434343739626166643438663238663564
  31643038313734663336393236353665303237323765373334616163613637626435313161353031
  65633233373362646562386537353064313432633862306430366531346332386433363336343033
  31623536626661303030656639623730383433336566366232313934323766636532323663643166
  33363638633439333766366465303034343331653933343737653261316462636663653966616166
  36306232623466636164663637376636333535373839316438393563313632623866653931373764
  31306531656566383637333261356165343232313935303233613036366239643732303664316431
  66333833623738636233373037343335653732323863363433313365393530626362363930653135
  30393664316532346464313434626464366334653966636662383431343365666164356131653636
  62383433373338323766633934643336383761663165663661326637373361303935373463323832
  61366365656239353337363232313862313866333465353164393339353964383731323535666266
  30363839623463656633663764353234656634366633363038396335316437643564616366623130
  31323435666631323934363339366531613362656262336562363163303037656638353634626638
  61663439313431353332653635323336343338306664333664333033396536356633316433353734
  63636439386630646233356437623963353436616438323335346534653133643030633666376336
  61373831373339393236363661653563376136626234326164323463333935396164303936633463
  31386439616536356639636239383133646431316564643435363134646362343261396161623638
  35613839326333326230393936626133313530386164393862313232313834613737623766396561
  37323337353661613761303761653363323661316434633864663564613233646364663037303264
  35326163363961393837616662323338363134373763383735663138393833393733393962656235
  38653436383261633461333764663633333566613530366334356635346662386462656266396462
  61353566336561333731363566376538396166313139353064613330306561623966353265383063
  61363534383936356630653132633135616562666635616363646632653264626635626538366636
  32363831386538303365613431633962346435303735366636653831353666636437383666376539
  64633265333435363438313364313535393138616230313065356262333038666133653936343335
  32346661306433333066643961393836356163386466386632626333346133613833396663373865
  66303433353938383436303662653639633431356637363830363866363065303638666231666564
  31316263336532373238313131363161653631363539383161353361613536636161333261646364
  63356535646563613339323362396333646135626463633639643735376461613039303637303938
  39333761353066396339313065343561353961333664323663373335373563613264353662383563
  62666137646230373732383338343930613535653864616632336539656434396663303363373134
  34303233643265346566656135613135303764343266336562323632383537393837363737363239
  33626236383532633432633437336231313734363034376338616235656330643334363635663536
  62663338396661653938336230653365613366646233373063643961366635623133626434343437
  61633762653432313762616236646331643838623062333464326130366539626461313534643463
  63346463356132326633333236653137346639333561313761326334646464653437383536643635
  33326261323637613538663533346332316239306439373034316630396231656464373161656630
  61333364646135663636663534373763663033653965656663366331383965366637386534373932
  30643531666439313730346430636364343633306135316139613162623261633937633064633335
  64626234656334366539373462663334383131353637613039666164613463393137616637666632
  6437

