
gnico_mail_password_vault: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34333334373132393039626239356566333061363531303230323465376337646332393661316364
  3639376666333832353838313266316434366564386266660a373465313931366663343332373061
  30623663653366313764343534656264326566366432383632666231646232373039323863613431
  6532343439383538650a663336343863363630343432393164346635383235663766303239383836
  32393834356563316365633463653331626235383763373539626637373332373163376632333265
  6364343930313266326533326536633837316566616561326661

# The email accounts
post_mail_accounts:
  - name: gnico-mail
    pwd: '{{ gnico_mail_password_vault }}'
