
gnico_mail_password_vault: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34333334373132393039626239356566333061363531303230323465376337646332393661316364
  3639376666333832353838313266316434366564386266660a373465313931366663343332373061
  30623663653366313764343534656264326566366432383632666231646232373039323863613431
  6532343439383538650a663336343863363630343432393164346635383235663766303239383836
  32393834356563316365633463653331626235383763373539626637373332373163376632333265
  6364343930313266326533326536633837316566616561326661

auth0_password_vault: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35626565306565646234633036623663306235343432323562313332656439323934646631613830
  3232383731616333366361363933386361336530363763630a366666363932306432643135333537
  66356336386331663764323533306665393561333635373139343136343830663066356337323135
  3739386366303130340a633838663439616666343431303034393866623036303139313338393965
  66626466666135306463616430653530383032333963383364373236303262643332653537353635
  3132343562643437636636333238656133376335623530643230

# The email accounts
post_mail_accounts:
  - name: gnico-mail
    pwd: '{{ gnico_mail_password_vault }}'
  - name: auth0-mail
    pwd: '{{ gnico_mail_password_vault }}'
