
srs_temp_dir: /tmp/srs
srs_temp_build_dir: /tmp/srs/build


srs_conf_file: /etc/default/postsrsd


# The secret to encode the sender mail with a signature in the name
# ie the weird character
# in SRS0=QYdl=AB=bedrooms.sk=mwbyef@bytle.net
srs_secret: '{{ srs_secret_vault }}'

srs_secret_vault: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64323464373036616263386164303439613737343132323336373932666131363632653132333235
  6463306435383164636432653930326134643635326339610a343532376633623131316232643731
  35363463613437613366323033643935303536376330653464383664643564306137363234336264
  3038666261636530610a653061316437306433636562333037653036663463383131616334303163
  34613964623133393532306235343834316532346532366435633737653366386231

