---


# Add the repo
# https://packagecloud.io/netdata/netdata
# /etc/yum.repos.d/*
# `el` in the baseurl means `entreprise linux`
#
- name: 'Netdata - Add the netdata repository'
  yum_repository:
    name: netdata
    description: Netdata Repo
    baseurl: https://packagecloud.io/netdata/netdata/el/$releasever/$basearch/
    gpgcheck: no
    repo_gpgcheck: no
    enabled: yes

# https://packagecloud.io/app/netdata/netdata/gpg
- name: "Netdata - Adds the gpg key"
  rpm_key:
    state: present
    key: https://packagecloud.io/netdata/netdata/gpgkey

# Install
- name: "Netdata - Install"
  yum:
    name: netdata
    state: present
    enablerepo: netdata




