# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
# Note that you can merge the PR automatically
# Example: https://github.com/RohanNagar/jmail/blob/master/.github/workflows/automerge-dependabot.yml
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "org.slf4j:*"
      - dependency-name: "org.apache.logging.log4j:*"
