# Cloudflare credentials
# https://certbot-dns-cloudflare.readthedocs.io/en/stable/
# Check the python cloudflare package linux 7 has not the version 2.3.1

dns_cloudflare_email: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31663632646366623666316631363230663632633636653737343632353335366162633063376331
  3635343533323065313230333335663566393865653538660a386561663838613166396134323064
  32613136346334393136346333333239306166323737336135656534353137643330326162633436
  6463343264393439390a643435363231306437633633333631383432383834333434656534326263
  39313863323132303563363064643030613831636364363462613366333130376562


dns_cloudflare_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37346339656232616666333366643138353636366363343261396561616234326533356532373438
  6166303466333337353963316635643933623161353436620a616465646434333662666630373237
  37616664646161356432653036633330353238363265666165383932636265613030393366333032
  3061626235643338330a613161646532636261376261643863373833383463666436666133336633
  63663132393965323135663961636239393434643165383137366431333266306338373335646334
  6332386239396562346261343034653530383137326638366135



