# Cloudflare credentials

dns_cloudflare_email: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66353238393331613261333835363536613035356131323633303837313664616330663532633966
  3330663335373434633630303731363537616561646337660a326431343066383161613034663063
  37616331616439306431366162363566636661373863653364626337376234656431613737363836
  3866393436313533650a323536336361393133626236363239393861376135336137383630663764
  36653832383734656139653763626266393832623963363064356462326533373837

dns_cloudflare_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63323566366565323239613634356234353565323630666163376531326332363631646131326636
  3631643739353461363565633864356666356339386631640a323336353538613838353463653938
  38646637303439353234366336663839363561326666393731623261613538616634316331383838
  6437326565306335390a363830393665373266613565616635313434326233633134366237613134
  62646364303166636539623139373331396436626535343831623636313539343966333362633331
  6432663537666434633233386565663662663263623431316633


