# All OVH information connection

dns_ovh_application_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64336565306331343865343165393532333563383561666633356661646664636536643561333130
  3062383031363564353434633932353331666266616139660a636661613435613230313432363231
  35313132663639366636303232626363666665636662623735313931333363366539636635313563
  3433343730656237610a363663626265393837303362626662633466316461393438353861626263
  38366539613533343264376433636335333134636166623262386665353933633533

dns_ovh_application_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66323961616433633237323865373662353938333832353864643161303039366338663938646266
  6436366634306232393433323434316331643966366239350a653738313363396438346562343231
  66653738663466633566393831366162316161386435333031333162323563636262303834386130
  6362636637643663350a376536626639356237306433343264316235366339633764336661343766
  66646532313666346463626537663235353462303735646433393638373830643032663239623564
  3765653234326363306435323639303038626330303938373461


dns_ovh_consumer_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38343562653833396134323537623162333762386565336164396333346334613232623263376431
  3537373361386362363938316333333439306533613362340a386661386266343532306430346163
  37323638396666323961303530363934613965366466386137623461343933346330666334373730
  3834363336396664320a366135336562303932343032343039643339613537623562313735323763
  31386563633030386466663465363332346335356461643537306263363062306633613536306166
  6138663130633065626134383266636365363861306530343934
