# All OVH information connection

dns_ovh_application_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32616430393364646637626432333364306461653830316632633432363264343134316563396430
  3831303730363938616436353164613839666632616335310a633836343635666263353963313439
  61613132393038363937393064306662623062323366643962326333363239313565333166383231
  6439393532613337320a653865313965346633623832313732333161613062393065643866323433
  36366636663664323039306666353938313634313462303262376265666533376561

dns_ovh_application_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37383166386461636235653065613461363864616439636363613162303463353165303831633062
  3164396534343239623464643663656166383666353330660a313134643539313432663931636266
  61316536646232646365666432653834363961623061343634396637626166353433393261326631
  6437333338333436620a613262396663623565353839613564623031616434316166633862363132
  64383763303932633634343637353965396131356436306266623832383861383661666136323531
  3465343434616339616639343339376233363865373062383336


dns_ovh_consumer_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31643964623930613830343464373733323139636630643066616461613265366630383165653064
  3262343163393138623661633731333564373161363362390a656561366563393434346233303730
  32383933336138653032393365643636653433396463346631373063636264633534653934643365
  6336393332343064360a656538336435313262656164366163346661626431623439386161333163
  62653534333763373730346263323363363665613063643663326532313534643730356531363361
  3537386336623966643333386233626333396539383664323430
