
- name: "Create presto group ({{ presto_group }})"
  group: name="{{ presto_group }}"

- name: "Create presto user"
  user:
    name: "{{ presto_user }}"
    group: "{{ presto_group }}"


- name: "Ensure Presto directories exist"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ presto_user }}"
    group: "{{ presto_group }}"
    mode: 0770
    recurse: true
  with_items:
    - "presto_server-{{ presto_version }}"
    - "{{ presto_etc_dir }}"
    - "{{ presto_data_dir }}"

- name: Symbolic link for presto server
  file:
    src: /opt/presto-server-{{ presto-version }}
    dest: {{ presto_base_dir }}
    state: link
