

- name: Update Postfix TLS configuration.
  notify: restart postfix
  lineinfile:
    dest: "{{ postfix_conf_path }}"
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^[#]{0,1}{{ item.name }}"
  with_items:
    - name: smtpd_reject_footer # Optional information that is appended after each Postfix SMTP server 4XX or 5XX response.
    - value: |
        For assistance, send an email to gnickeau@gmail.com
        and provide the following information in your problem report:
           * time ($localtime),
           * client ($client_address)
           * and server ($server_name).
