
# Create the mail account
- name: "Create the users"
  user:
    name: '{{ item.name }}'
    comment: 'Mail User {{ item.name }}'
    state: present
    #create_home: no
    system: true
    password: "{{ item.pwd | password_hash('sha512') }}"
  with_items: '{{ post_mail_accounts }}'

