---
# defaults file for nexus

nexus_group: nexus
nexus_user: nexus

# The location where the tar installation file is extracted
nexus_root: /opt/nexus

nexus_pid_dir: /var/run/nexus
nexus_shell: /sbin/nologin

# Web Url
# http://host:port/context/
nexus_host: '{{ ansible_hostname }}'
nexus_port: 8081
# should be in the form /nexus/ (not nexus or /nexus)
nexus_context_path: /

# Used by nginx to reach nexus directly
nexus_fqdn: '{{ ansible_fqdn }}'

# Ssl

nexus_ssl: False
nexus_ssl_port: 8443
nexus_ssl_keypass: changeit
nexus_ssl_storepass: changeit




# latest version is here
nexus_download_base_url: https://download.sonatype.com/nexus/3

# Full list at https://help.sonatype.com/repomanager3/download/download-archives---repository-manager-3
nexus_version: 3.19.1-01

# The name of the file to download
nexus_distribution_name: 'nexus-{{ nexus_version }}-unix.tar.gz'

# An application directory
nexus_application_directory_name: 'nexus-{{ nexus_version }}'
nexus_application_directory: '{{ nexus_root }}/{{ nexus_application_directory_name }}'
# Data directory, sometimes called the "Sonatype Work" directory
nexus_data_directory: '{{ nexus_root }}/sonatype-work/nexus3'

# Will redownload the file
nexus_download_force: no
# Download destination directory
nexus_install_temp: /tmp/nexus

# sometimes seen as nexus-current
nexus_link: nexus-latest

# ip address or range of ip where we open the firewall
nexus_white_ip_address: []


# Memory
nexus_java_memory: 512

