# Prometheus conf
# https://prometheus.io/docs/operating/configuration

# The global block Prometheus server's global configuration
global:
  scrape_interval:     15s # how often Prometheus will scrape targets
  evaluation_interval: 15s # how often Prometheus will evaluate rules
  # scrape_timeout is set to the global default (10s).

# The location of any rules we want the Prometheus server to load
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first.rules"
# - "second.rules"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# The scrape jobs
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:
  # Prometheus scrapes itself
  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:{{ prometheus_port }}']
  - job_name: "node_exporter"
    static_configs:
      - targets: [ 'localhost:{{ prometheus_node_exporter_port }}' ]
  # https://learn.netdata.cloud/docs/exporting/prometheus#querying-metrics
  - job_name: "netdata"
    static_configs:
      - targets: [ 'localhost:{{ netdata_default_port }}/api/v1/allmetrics?format=prometheus&help=yes' ]
