---
# handlers file for nexus

- name: 'nexus reload'
  become: yes
  systemd:
    name: 'nexus.service'
    enabled: 'yes'
    daemon_reload: yes
    state: restarted


- name: reload nginx
  become: true
  systemd:
    state: reloaded
    name: nginx
