---

cassandra_java_version: '1.8'

cassandra_package_repo: cassandra

cassandra_cluster_name: 'Bytle'

# conf is a symlink to default.conf
# we don't copy the file just tweak the content
cassandra_conf: /etc/cassandra/default.conf

# Memroy
# Override these to set the amount of memory to allocate to the JVM at
# start-up. For production use you may wish to adjust this for your
# environment. MAX_HEAP_SIZE is the total amount of memory dedicated
# to the Java heap. HEAP_NEWSIZE refers to the size of the young
# generation. Both MAX_HEAP_SIZE and HEAP_NEWSIZE should be either set
# or not (if you set one, set the other).
#
# The main trade-off for the young generation is that the larger it
# is, the longer GC pause times will be. The shorter it is, the more
# expensive GC will be (usually).
#
# The example HEAP_NEWSIZE assumes a modern 8-core+ machine for decent pause
# times. If in doubt, and if you do not particularly want to tweak, go with
# 100 MB per physical CPU core.
#MAX_HEAP_SIZE="4G"
#HEAP_NEWSIZE="800M"
# Total  memory size=MAX_HEAP_SIZE+HEAP_NEWSIZE*cores ?

cassandra_max_heap_size: "800M"
cassandra_heap_newsize: "200M"
