---

galaxy_info:
  description: 'Ansible role to install nexus'
  license: 'MIT'
  min_ansible_version: '2.7'
  github_branch: 'master'

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  # https://galaxy.ansible.com/api/v1/platforms/?name__icontains=EL
  platforms:
    - name: EL
      versions:
        - 7

  # List tags for your role here, one per line. A tag is a keyword that describes
  # and categorizes the role. Users find roles by searching for tags. Be sure to
  # remove the '[]' above, if you add tags to this list.
  #
  # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
  #       Maximum 20 tags per role.
  galaxy_tags:
    - centos7
    - yum
    - repository


#dependencies:
#  - role: openjdk
