
# the installation path is
# /etc/alternatives/java_sdk_xxx_openjdk/
- name: Install {{ openjdk_package_name }}
  yum:
    name: "{{ openjdk_package_name }}"
    state: latest
    update_cache: yes
  tags: [ install, yum ]

- name: Ensure java profile
  template:
    src: java.sh
    dest: /etc/profile.d/java.sh
    mode: 0644
  tags: config
