

# version
# https://github.com/restic/restic/releases/tag/v0.16.0
restic_version: 0.16.0
restic_checksum: sha256:492387572bb2c4de904fa400636e05492e7200b331335743d46f2f2874150162
# the user that runs the executable
restic_user: restic
# the group that may run restic
restic_group: restic

# Backup are exclusive
# the repo for the backup
restic_repository_datacadamia: 'rclone:{{ rclone_restic_remote_name }}:{{ rclone_restic_remote_bucket_name }}/datacadamia'

# the repo password
restic_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34643334366432393839386538613039633564326237343732323130343634326632663832393565
  3766346335656462383432356132363631396265333833380a343664666334616333303737636663
  32356335303132356463653365376338333830383466353538613564616636633734633739643832
  6438323732633631380a346131333238373265663336353633346565353032386130663264393630
  34373562323661373330356236643565613266363330643937316130646163313862

# Backup path
restic_config: '/home/{{ restic_user }}/.config'
restic_daily_backup_paths: '{{ restic_config }}/restic-daily-backup-paths.txt'
restic_hourly_backup_paths: '{{ restic_config }}/restic-hourly-backup-paths.txt'

rclone_version: v1.64.0
rclone_cpu: amd64

rclone_restic_remote_name: 'idrive-restic'
rclone_restic_remote_bucket_name: 'restic'
rclone_restic_remote_access_key_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64383362353934383838353838663237366538346264313038343933633735643961313166653831
  3861663236386466363732363830363062333034373834630a656432636261646564336339656161
  36653135343365636430333062333463333531326236303261303136326532316235616633366362
  3337613939663265340a346139666265366537393332356631616163323666633838353162653731
  38666461613864386363393563346633346465323937396336613036333238303935
rclone_restic_remote_access_key_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62386630633030613964613866653362623861643931646136356564306235356664633063343930
  3434393161313261633566323135346164373937646532380a346265313466363736376132343935
  36373939306263323266366536656433346137363433643665373839613637393930333832373530
  6530613930316466320a393836626334323964316363633735303534346162646562616431383966
  39653766393431633534346435383664646132356164326166313034353132323562356139643532
  3632663332623264646562613735313337393366666536383330
rclone_restic_remote_access_key_endpoint: 'h0k0.ca.idrivee2-22.com'
