# https://docs.docker.com/compose/multiple-compose-files/include/
include:
  - ../core/compose.yml
services:
  dockerui:
    image: joinsunsoft/docker.ui
    networks:
      - caddy
    labels:
      caddy: dockerui.eraldy.com
      caddy.reverse_proxy: "{{upstreams 8999}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
