- name: Postgres - Install Root
  become: true
  import_tasks: 'postgresql-install.yml'
  tags: pg_install

- name: Postgres - Configuration
  become: true
  become_user: postgres
  import_tasks: 'postgresql-conf.yml'

- name: Postgres - Users
  become: true
  become_user: postgres
  import_tasks: 'postgresql-db-users.yml'
  tags: pg_db_users

