
- name: Postgres | Configuration template
  template:
    src: postgresql.conf.ini
    dest: "{{ pg_data }}/postgresql.conf"
    owner: postgres
    group: postgres
  notify:
    postgres_restart

- name: Copy init conf script
  template:
    src: 'db-conf.sql'
    dest: "{{ pg_scripts }}/db-conf.sql"
    owner: postgres
    group: postgres
  tags: postgres-sql-conf

- name: Executing conf script
  shell:
    cmd: "/bin/psql -d {{ pg_combo_db }} -f {{ pg_scripts }}/db-conf.sql"
  args:
    executable: /bin/bash
  tags: postgres-sql-conf
