# a prefix
backend_app_name: backend

# install path
backend_install_path: '/opt/{{ backend_app_name }}'
backend_cache_dir: '{{ backend_install_path }}/cache'

# port
backend_port: 8083

# The endpoints
# Api
backend_fqdn_api: 'api.bytle.net'
backend_fqdn_api_log_dir: '{{ bytle_base_log_dir }}/{{ backend_fqdn_api }}'

# Analytics
backend_fqdn_analytics: 'analytics.bytle.net'
backend_fqdn_analytics_log_dir: '{{ bytle_base_log_dir }}/{{ backend_fqdn_analytics }}'

# Auth
# User password
# user that will run the jar
backend_user_name: '{{ backend_app_name }}'
backend_user_group: '{{ backend_app_name }}'
backend_user_pwd: '{{ backend_user_pwd_vault }}'
backend_user_pwd_vault: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35313462656234333235363538646235306338386237623663383530323662333963666363336235
  3738383166353533626262303337313939343035316662370a343035323061656137623436616263
  65343564303335633965653237303061386437326634313962616432393433383334376663333930
  3635373465393338630a626230653166376631323033303334666435313234383330373963666664
  37656635396262623139353937623931623562653062616236326532343265323661

# The password of the repository manager
# from where the jar can be downloaded
# deprecated
# Download info (snapshot latest)
backend_repository_url: http://127.0.0.1:8082/repository/maven-snapshots
backend_repository_user: admin
backend_repository_pwd: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65633361396165313764633934356533373032306161303566666466326233323036323139376664
  3738666238663039333463616632333134353963396633340a363036316266626639306430333630
  61313161366332393065366431356261356666663737656138386363666134356333383936643835
  3838316535383264330a363132616666663664396137323430396634343263666462326135373136
  36353562613033356138343137633962356132373534323565636665656139363966
