

# Define configuration for health_alarm_notify.conf.
# Example:
# netdata_health_alarm_notify_configs:
#   https_proxy: http://localhost:3128
#   SLACK_WEBHOOK_URL: https://hooks.slack.com/...
netdata_alarm_notify_configs: {}


# Defines how often a critical alarm is repeated
netdata_default_repeat_critical: never

# Defines how often a warning alarm is repeated
netdata_default_repeat_warning: never

#Define custom_sender function in health_alarm_notify.conf
#only the body of the function should be in there
#Exemple: netdata_custom_sender_function: "curl -X POST url"
# netdata_custom_sender_function: ""
