# When set to save netdata will save its round robin database on exit and
# load it on startup. When set to map the cache files will be updated in
# real time (check man mmap - do not set this on systems with heavy load or
# slow disks - the disks will continuously sync the in-memory database of
# netdata). When set to ram the round robin database will be temporary and it
# will be lost when netdata exits.
netdata_memory_mode: save

# Defines if Netdata should store data in a backend
netdata_configure_archive: false

# https://github.com/firehol/netdata/wiki/netdata-backends
# Defines the backend type as one of
# graphite | opentsdb | json
netdata_archive_type: 'opentsdb'

# Defines the host(s) and ports netdata should send data to
netdata_archive_destination:
  - localhost
  # - "{{ vip }}:5252"

# Defines how to send the archive data as one of
# as collected, average, sum
netdata_archive_data_source: 'average'

# Defines a prefix for the archive data
netdata_archive_prefix: 'netdata'

# Defines how often to send archive data in seconds
netdata_archive_update: 1


# Defines the number of update intervals
# after which dataloss occurs
netdata_archive_buffer_on_failures: 30

# Defines when to timeout sending to a backend in milliseconds
netdata_archive_timeout: 20000

# Defines if Netdata sends metric names or UUIDs
netdata_archive_send_names: true
