---

#########################
# Global conf
#########################
# Defines an installation prefix added to all netdata directories
# May be set to /opt
netdata_install_path: '/opt'

# The host name displayed in netdata
netdata_hostname: "{{ ansible_hostname }}"

# The number of entries the netdata daemon will by default keep in memory
# for each chart dimension.
netdata_history: 3996


#########################
# Configuration variable
#########################
# Defines if Netdata should be configured
netdata_config: false
# Defines whether Netdata health should be enabled
netdata_health_enabled: false
# Defines if Netdata health alarms should be configured
netdata_alarm_configure: false
# Defines if Netdata host should be enabled as a registry
netdata_registry_enabled: false
# Defines if Netdata streaming should be configured
netdata_stream_enabled: false
# Defines if the Netdata backend is enabled
netdata_archive_enabled: 'false'





#########################
# Command variable
#########################
# Defines if Netdata should be uninstalled
# Caution: This does not prompt for uninstall as the original script
# was intended.
# https://github.com/firehol/netdata/wiki/Installation#uninstalling-netdata
netdata_uninstall: false
# Defines if Netdata should be updated
# Not the same as auto_updates
netdata_update: false
# Force the update. Sometimes the update script skips installing new plugins.
netdata_update_force: false
