## Contains path to directory and configuration files
## This should normally not change

# Defines where netdata will be installed
netdata_prefix: '{{ netdata_install_path }}/netdata'

# The config dir
netdata_user_config_dir: '{{ netdata_prefix }}/etc/netdata'

# The plugin dir
netdata_plugin_dir: '{{ netdata_prefix }}/usr/libexec/netdata'

# The daemon dir
netdata_daemon_path: '{{ netdata_prefix }}/usr/sbin/netdata'

# The log dir
netdata_log_dir: '{{ netdata_prefix }}/var/log/netdata'

# The web dir
netdata_web_dir: '{{ netdata_prefix }}/usr/share/netdata'

# The cache dir
netdata_cache_dir: '{{ netdata_prefix }}/var/cache/netdata'

# The db dir
netdata_db_dir: '{{ netdata_prefix }}/var/lib/netdata'

# Defines location of Netdata configuration file
# Default to: /etc/netdata/netdata.conf
netdata_config_file: '{{ netdata_user_config_dir }}/netdata.conf'

# Defines location of Netdata health_alarm_notify.conf
netdata_alarm_config_file: '{{ netdata_user_config_dir }}/health_alarm_notify.conf'

# Defines path to alarm-notify.sh
netdata_health_alarm_script: '{{ netdata_plugin_dir }}/plugins.d/alarm-notify.sh'


# Defines location of Netdata stream configuration file
netdata_stream_config_file: '{{ netdata_user_config_dir }}/stream.conf'
