# Adds installer flag to enable auto updates
# https://docs.netdata.cloud/packaging/installer/update/#auto-update
netdata_auto_updates:
  enabled: true
  day: "*"
  hour: 6
  minute: 0
  user: root
  weekday: "*"
  # WARNING: when you set this variable to 'true' and are migrating from an old version
  # of Netdata (< v1.11.0) then the cron will be removed from your system.
  # You will then need to launch the netdata installer manually to make sure
  # netdata installs the cron by itself with: `./netdata-installer.sh --auto-update`
  clean_legacy_cron: true

# The frequency in seconds, for data collection
netdata_update_every: 1

