
- name: Apps
  become: true
  include: apps.yml
  tags: apps

- name: Tower
  become: true
  include: tower.yml
  tags: app-tower

- name: Tabli
  become: true
  include: tabli.yml
  tags: app-tabli

- name: Tabli
  become: true
  include: smtp-inbox.yml
  tags: app-inbox
