gnico_app_name: gnico
# user that will run the jar
gnico_user_name: '{{ gnico_app_name }}'
gnico_user_group: '{{ gnico_app_name }}'

# install path
gnico_install_path: '/opt/{{ gnico_app_name }}'

# Download info (snapshot latest)
gnico_repository_url: http://127.0.0.1:8082/repository/maven-snapshots
gnico_repository_user: admin
gnico_repository_pwd: changeme


