---

- name: Wireguard | Install
  become: true
  tags: wg-install
  when: ansible_distribution == 'Fedora'
  block:
    - include_tasks: 'wireguard_install.yml'

- name: Wireguard | Install
  become: true
  tags: wg-firewall
  when: ansible_distribution == 'Fedora'
  block:
    - include_tasks: 'wireguard_firewall.yml'
