---

# App environment (suffix, prefix) use everywhere
prometheus_name: prometheus

# The user
prometheus_user_name: prometheus
prometheus_user_group: prometheus
prometheus_user_home: '/home/{{ prometheus_user }}'

# The target installation environment
prometheus_base: /opt
prometheus_home: "{{ prometheus_base }}/{{ prometheus_name }}"
prometheus_bin_file: "{{ prometheus_home }}/prometheus"
prometheus_log_dir: "{{ prometheus_home }}/log"
prometheus_config_dir: "{{ prometheus_home }}/custom/conf"
prometheus_repositories: "{{ prometheus_home }}/prometheus-repositories"
prometheus_data_name_dir: data
prometheus_data_dir: "{{ prometheus_home }}/{{ prometheus_data_name_dir }}"
prometheus_data_path_relative: "{{ prometheus_data_name_dir }}/prometheus" # use in the conf file
prometheus_port: 3001
prometheus_fqdn: "{{ prometheus_name }}.bytle.net"


# The temp installation environment
prometheus_install_dir: '/tmp/{{prometheus_user_name}}'

# Node Exporter
prometheus_node_exporter_version: 1.0.0-rc.0
prometheus_node_exporter_binary_url: "https://github.com/prometheus/node_exporter/releases/download/v{{prometheus_node_exporter_version}}/node_exporter-{{prometheus_node_exporter_version}}.linux-amd64.tar.gz"
prometheus_node_exporter_checksum: md5:02b59d17fc7b58df81632f9fbdce01b5
prometheus_install_file: '{{prometheus_install_dir}}/prometheus.zip'

