---

# App environment (suffix, prefix) used everywhere
prometheus_name: prometheus

# The temp installation environment
prometheus_install_dir: '/tmp/{{prometheus_user_name}}'

# The user
prometheus_user_name: prometheus
prometheus_user_group: prometheus
prometheus_user_home: '/home/{{ prometheus_user }}'

# The target installation environment
prometheus_base: /opt/prometheus

################
## Prometheus
################
# The prometheus binary data
prometheus_version: 2.48.0-rc.0
prometheus_binary_name: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_binary_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_binary_name }}.tar.gz"
prometheus_checksum: sha256:44c384d88843af110b18f203db9e682b61b6f703026cf45a015e88705050d4de

# Service
prometheus_port: 9090

# File System
prometheus_home: "{{ prometheus_base }}/{{ prometheus_name }}"
prometheus_bin_file: "{{ prometheus_home }}/prometheus"
prometheus_log_dir: "{{ prometheus_home }}/log"
prometheus_config_dir: "{{ prometheus_home }}/custom/conf"
prometheus_repositories: "{{ prometheus_home }}/prometheus-repositories"
prometheus_data_name_dir: data
prometheus_data_dir: "{{ prometheus_home }}/{{ prometheus_data_name_dir }}"
prometheus_data_path_relative: "{{ prometheus_data_name_dir }}/prometheus" # use in the conf file


################
## Prometheus Node Exporter
################
prometheus_node_exporter_home: "{{ prometheus_base }}/node_exporter"
prometheus_node_exporter_version: 1.0.0-rc.0
prometheus_node_exporter_name: "node_exporter-{{prometheus_node_exporter_version}}.linux-amd64"
prometheus_node_exporter_binary_url: "https://github.com/prometheus/node_exporter/releases/download/v{{prometheus_node_exporter_version}}/{{ prometheus_node_exporter_name }}.tar.gz"
prometheus_node_exporter_checksum: md5:02b59d17fc7b58df81632f9fbdce01b5
prometheus_node_exporter_port: 9100


################
## Prometheus Remote Write
################
grafana_cloud_prometheus_url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
grafana_cloud_prometheus_user: 182629
grafana_cloud_prometheus_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38313030356639313531303531633466646530653864623536623762373338613231366535373038
  3131666165653761333635373934613039393334633130660a323935656534383730623532613730
  38623736303230306139313631396433313936356530613535616535616366333531343830356639
  3339313436613034360a653131353431666664303365353138306461383636363530373533323833
  61393030643865343631663634633430316665306463333364376562653664313538623835323265
  61653561623065633135353436663636373862353734613164376537366434626131363466376465
  34393961663634386535356531303764376432663464613534363837313539656332343138653263
  37653837396438373732646464316531366166613233373135393031653039343339363030313563
  62656166663161633764383466393932373865633031626235633339386363303461386434636463
  33303732366662346539393263626533323830323366323737383963663038646564306462653665
  31323363663634363838616130623838653138343332313438343537306566336636316465343436
  32613965353962653832643361356436363362386632346430613363633238663236336636636436
  3864
