
- name: Fail if not Redhat
  fail:
    msg: "This role supports only the Redhat family. This computer is installed on the following OS ({{ ansible_os_family }})"
  when: ansible_os_family != "RedHat" # Centos

- name: Php NewRelic Infra Installation
  tags: newrelic_infra
  become: true
  import_tasks: 'root_newrelic_infra.yml'

- name: Php NewRelic Infra Nginx Extension
  tags: newrelic_infra
  become: true
  import_tasks: 'root_newrelic_infra_nginx.yml'


