# sudo yum install newrelic-php5
# Too much data
# https://one.newrelic.com/data-management-hub
# https://docs.newrelic.com/docs/apm/agents/php-agent/configuration/php-agent-configuration/
# https://docs.newrelic.com/docs/apm/agents/php-agent/configuration/php-agent-configuration/#inivar-tt-settings
- name: 'New Relic - Disable Tracing, take too much data'
  lineinfile:
    dest: "/etc/php.d/newrelic.ini"
    state: present
    regexp: "^[;]{0,1}newrelic.transaction_tracer.enabled"
    line: "newrelic.transaction_tracer.enabled = false"
  notify:
    newrelic_infra_restart
- name: 'New Relic - Disable Tracing, take too much data'
  lineinfile:
    dest: "/etc/php.d/newrelic.ini"
    state: present
    regexp: "^[;]{0,1}newrelic.transaction_tracer.enabled"
    line: "newrelic.transaction_tracer.enabled = false"
  notify:
    newrelic_infra_restart
