
# A name
nginx_pagespeed_name: 'ngx_pagespeed'
nginx_pagespeed_module_file_name:  '{{nginx_pagespeed_name}}.so'

# Pagespeed is based on psol (PageSpeed Optimization Libraries)
# It's also downloaded
nginx_psol_version: 1.13.35.2
nginx_psol_bit_size_name: 'x64'
nginx_psol_archive: '{{ nginx_psol_version }}-{{ nginx_psol_bit_size_name }}.tar.gz'

# Pagespeed
# Version can be checked at https://www.modpagespeed.com/doc/release_notes
nginx_pagespeed_version: '{{ nginx_psol_version }}-stable'
nginx_pagespeed_archive:  'v{{ nginx_pagespeed_version }}.zip'
nginx_pagespeed_archive_dir_name: 'incubator-pagespeed-ngx-{{ nginx_pagespeed_version }}' # The directory name in the archive
