---

# App environment (suffix, prefix) use everywhere
gogs_name: gogs
gogs_binary_url: https://github.com/gogs/gogs/releases/download/v0.11.91/linux_amd64.zip

# The user
gogs_user: gogs
gogs_user_group: gogs
gogs_user_home: '/home/{{ gogs_user }}'

# The target installation environment
gogs_base: /opt
gogs_home: "{{ gogs_base }}/{{ gogs_name }}"
gogs_bin_file: "{{ gogs_home }}/gogs"
gogs_log_dir: "{{ gogs_home }}/log"
gogs_config_dir: "{{ gogs_home }}/custom/conf"
gogs_repositories: "{{ gogs_home }}/gogs-repositories"
gogs_data_name_dir: data
gogs_data_dir: "{{ gogs_home }}/{{ gogs_data_name_dir }}"
gogs_data_path_relative: "{{ gogs_data_name_dir }}/gogs" # use in the conf file
gogs_port: 3001
gogs_fqdn: "{{ gogs_name }}.bytle.net"

## Conf (app.ini)
gogs_mail_enabled: false
gogs_mail_user: foo@example.com
gogs_mail_password: changeme
gogs_mail_host: smtp.example.com:587
gogs_secret_key: "{{ gogs_mandatory_secret_key }}"


# The temp installation environment
gogs_install_dir: '/tmp/{{gogs_user}}'
gogs_install_file: '{{gogs_install_dir}}/gogs.zip'

