# Install from the remi repo

- name: Php Installation is Php version and OS version dependent
  debug:
    msg:
      ansible_distribution: '{{ ansible_distribution }}'
      php_version: '{{ php_version }}'
      ansible_distribution_major_version: '{{ ansible_distribution_major_version }}'


- name: Install Php 7.4 on Centos 7
  when: ansible_distribution == 'CentOS' and php_version == '7.4' and ansible_distribution_major_version == '7'
  include_tasks: 'root_install_php_7.4_centos_7.yml'

- name: Install Php 8.2 on Fedora 38
  when: ansible_distribution == 'Fedora' and php_version == '8.2' and ansible_distribution_major_version == '38'
  include_tasks: 'root_install_php_8.3_fedora_38.yml'
