---

- name: Drill | Download Server File
  get_url:
    url: "https://dlcdn.apache.org/drill/drill-{{ drill_version }}/apache-drill-{{ drill_version }}.tar.gz"
    dest: "/tmp/apache-drill-{{ drill_version }}.tar.gz"
    owner: "{{ drill_user }}"
    group: "{{ drill_group }}"
    checksum: "{{ drill_checksum }}"
    force: no # download only if not already downloaded

- name: Drill | Create Server Directory
  file:
    path: '{{ drill_server_dir }}'
    state: directory
    mode: 0755
    group: "{{ drill_group }}"
    owner: "{{ drill_user }}"

- name: Drill | Unzip tarball
  become: true
  become_user: "{{ drill_user }}" # otherwise the permissions are not right (https://github.com/ansible/ansible/issues/35426#issuecomment-679923154)
  unarchive:
    src: "/tmp/apache-drill-{{ drill_version }}.tar.gz"
    dest: "{{ drill_opt_dir }}"
    group: "{{ drill_group }}"
    owner: "{{ drill_user }}"
    creates: "{{ drill_server_dir }}/README.md" # run only if this file does not exists
    copy: false

- name: Drill | Symbolic link for drill server
  file:
    src: '{{ drill_server_dir }}'
    dest: '{{ drill_home_dir }}'
    state: link
