
- name: Copy the systemd drill.service file
  template:
    src: drill.service
    dest: /etc/systemd/system/drill.service
    mode: 0644

- name: Drill reload
  systemd:
    name: 'drill.service'
    enabled: 'yes'
    daemon_reload: yes
    state: restarted


