all: # keys must be unique, i.e. only one 'hosts' per group
  children:  # key order does not matter, indentation does
    ovh: # groups
        hosts:
          # (located in Noord-Amerika, Canada, Beauharnois (BHS)
          beau: # beau - ansible_user and ansible_password are in variables given inline
            # the host to connect to
            ansible_host: vps-427a1b7c.vps.ovh.ca
            # hostname should be the static hostname in a FQDN format.
            hostname: beau.bytle.net
            ansible_user: '{{ ssh_user_name }}'
            ansible_password: '{{ ssh_user_password }}'
            ansible_port: 22
            ansible_become_pass: '{{ ssh_user_password }}'
            # Version
            openjdk_version: '11'
            php_version: '7.4'
