
- name: fpm_reload
  systemd:
    name: "php-fpm"
    state: reloaded
  become: true

- name: phpctl reload
  become: true
  systemd:
    name: '{{ phpctl_name }}'
    state: reloaded
    daemon_reload: yes
