---

# A new Linux user cassandra will get created as part of the installation. The Cassandra service will also be run as this user.
- name: Cassandra - Install
  yum:
    name: cassandra
    enablerepo: '{{ cassandra_package_repo }}'
    state: present
    update_cache: yes

