---
# handlers file for ansible-netdata
#
- name: netdata reload
  become: true
  systemd:
    name: "netdata"
    daemon_reload: true

- name: netdata restart
  become: true
  systemd:
    name: "netdata"
    state: "restarted"
    enabled: true

- name: netdata start
  become: true
  systemd:
    name: "netdata"
    state: "started"
    enabled: true

- name: netdata stop
  become: true
  systemd:
    name: "netdata"
    state: "stopped"
    enabled: true


