---

- name: 'restart wg'
  become: yes
  systemd:
    name: '{{ wg_service }}'
    enabled: 'yes'
    daemon_reload: yes
    state: restarted

- name: "firewalld reload"
  become: yes
  systemd:
    state: restarted
    name: firewalld
