# https://docs.docker.com/compose/multiple-compose-files/include/
include:
  - ../core/compose.yml
services:
  chronicle:
    image: soulteary/cronicle
    networks:
      - caddy
    labels:
      caddy: chronicle.eraldy.com
      caddy.reverse_proxy: "{{upstreams 3012}}"
    restart: unless-stopped

