services:
  caddy:
    volumes:
      # path is relative to the current directory
      # of the executed command not to the file
      - ../../certs:/certs
  portainer:
    labels:
      caddy_1: portainer.eraldy.dev
      caddy_1.tls: /certs/cert.pem /certs/key.pem
      caddy_2: portainer-agent.eraldy.dev
      caddy_2.tls: /certs/cert.pem /certs/key.pem
