# fly.toml app configuration file generated for eraldy-monitor on 2023-10-11T16:57:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eraldy-monitor"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"
