---
# port


# User to connect
ssh_user_name: 'nickeau'
ssh_user_password: '{{ ssh_user_password_vault }}' #  to avoid argument 1 must be string
ssh_user_password_vault:  !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32626436303536616163366133623338343563393932353734353766366362343261303737353834
  3434323335653936376461303062363234386664623432390a343539636164353361326165333735
  35386365326164663432663164626363613162623961623966343730663035336138386133663336
  6265383461333234340a356365643234366239366339373333393537336661633965326236386632
  36356539643939616635393234653834353466626466383135336631346364383731


# Root
root_name: 'root'
root_password: '{{ root_password_vault }}' #  to avoid argument 1 must be string
root_password_vault: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38613863336265643965653332323638343563333961613633626665303138616461623261313434
  6465663739396437626636613036643663623763306335350a643930656538383766393534306365
  65383161376236623663393732306563346664376630303265353937336165346430306338613366
  3561626133383562380a373139393438663939333765346664633537653739613032336139653034
  6139


# Ansible
ansible_user: '{{ ssh_user_name }}'
ansible_password: '{{ ssh_user_password }}'
