
- name: Ngxin Admin | Allow access to the log to all nginx group users
  file:
    path: '/var/log/nginx'
    state: directory
    mode: 0770
    owner: 'nginx'
    group: 'nginx'
    recurse: yes

# Trick - The install should be from the source because of the module
# If we do that there is no update anymore possible, therefore we don't
#- name: Nginx | Disallow update because of the module
#  lineinfile:
#    dest: /etc/yum.conf
#    state: present
#    regexp: "^exclude"
#    line: "exclude=nginx"

