
pg_bin: /usr/pgsql-15/bin

# where are the data (where to copy the conf file)
pg_data: /var/lib/pgsql/15/data

# where to copy the scripts
pg_scripts: /var/lib/pgsql/15

# the database to create
pg_combo_db: combo # the name of the combo database
pg_databases:
  - name: "{{ pg_combo_db }}"
    # https://www.postgresql.org/docs/current/multibyte.html#MULTIBYTE-CHARSET-SUPPORTED
    encoding: UTF-8

# the users
pg_users:
  combo:
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65633033643934376138363465323461323533303761613033666262333138373363383862623636
      3937333366393963326534326161333665353562343561610a616137633739323738343632333934
      35383633393164336135393265363530626662663766333766373166306161616533343561643663
      3763623037346431640a306364643233616139643566343633356439353232356331346334373336
      66326265633737383735353737383339336330343162666663363261643836393862
    db: "{{ pg_combo_db }}"
    # role_attr_flags:
    expires: infinity
    priv: ALL


# the url
pg_combo_user: 'combo'
pg_combo_url: "jdbc:postgresql://localhost:5432/{{ pg_users[ 'combo' ].db }}"
pg_combo_password: "{{ pg_users[ 'combo' ].password }}"
