# The secret configurations
users:
  inbox.eraldy.com:
    dmarc:
      mailbox:
        s3.access.key.id: 3WsquWDtCYkFD8shmFZU
        s3.secret.access.key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33656465313561623563633439623432363163316637316364666162623763313635623630386330
          6466333436646236656237303863336535636337633930620a613865643737663763613164363863
          39386432626536353932663239383931346364393466653037373161653832636130316638343438
          3962656534663064630a333964343964363035353162383465316562396661363530373037636437
          61646561366636663237666235396534363666323066393431396534353439333734666130613964
          3934353763623165383065323039336533376663333834653365
