---
jdbc.url: "{{ pg_combo_url }}"
jdbc.user: "{{ pg_combo_user }}"
jdbc.password: "{{ pg_combo_password }}"

# the dkim public key DNS selector
mail.dkim.selector: "eraldy"
# the dkim private key (PKCS#8 format)
mail.dkim.private_key: >
  {{ tower_conf_dkim_private_key }}
# For the encryption of data in url
secret.url.data.encryption: '{{ tower_conf_secret_url_data_encryption }}'
# for the encryption of id
secret.id: '{{ tower_conf_secret_id }}'
# for the encryption of password that should be re-read such as smtp password
secret.symmetric.data.encryption: '{ { tower_conf_secret_symmetric_data_encryption }}'
# a nonce, api key for the superuser,
superuser.token: '{{ tower_conf_superuser_token }}'
