---
- hosts: ovh
  tasks:
  roles:
    - name: Os Common (securistation)
      role: os
      tags: os
    - name: Install Nginx
      role: nginx
      tags: nginx
    - name: Install openjdk
      role: openjdk
      tags: openjdk
#    - name: Install nexus
#      role: nexus
#      nexus_version: 3.19.1-01
#      tags: nexus
    - name: Install netdata
      role: netdata
      tags: netdata
    - name: Install apps
      role: apps
      tags: apps
    - name: Install Gogs
      role: gogs
      tags: gogs
    - name: Install Prometheus Exporter
      role: prometheus
      tags: prometheus
    - name: Install Certbot and asks for the certificate
      role: certbot
      tags: certbot
    - name: Install Php
      role: php
      tags: php
    - name: Install postfix
      role: postfix
      tags: postfix
    - name: Install drill
      role: drill
      tags: drill
    - name: Install cassandra
      role: cassandra
      tags: cassandra
    - name: Install Chrome
      role: chrome
      tags: chrome
    - name: Install NewRelic
      role: newrelic
      tags: newrelic
    - name: Install Postgres
      role: postgres
      tags: postgres
    - name: Install Restic Backup
      role: restic
      tags: restic
    - name: Install Wireguard (VPN)
      role: wireguard
      tags: wireguard
