---
- hosts: ovh
  tasks:
  roles:
    - role: ovh-sec
      tags: 'sec'
    - name: Install openjdk
      role: openjdk
      openjdk_version: 1.8.0
      tags: java
    - name: Install nexus
      role: nexus
      nexus_version: 2.14.3-02
      nexus_home: /opt/nexus
      nexus_port: 8081
      tags: nexus

  
