---
- hosts: ovh
  tasks:
  roles:
    - role: ovh-sec
      tags: 'sec'
    - name: Install Nginx
      role: nginx
      tags: nginx
    - name: Install openjdk
      role: openjdk
      openjdk_version: 1.8.0
      tags: java
    - name: Install nexus
      role: nexus
      nexus_version: 3.19.1-01
      tags: nexus
    - name: Install netdata
      role: netdata
      tags: netdata


