# We don't use that anymore because the restic binary
# is not up-to-date

# Same repo definition as here
# https://copr.fedorainfracloud.org/coprs/copart/restic/repo/epel-7/copart-restic-epel-7.repo
- name: Restic - Add Copr Restic repo
  yum_repository:
    name: copart-restic
    description: Copr repo for restic owned by copart
    baseurl: https://download.copr.fedorainfracloud.org/results/copart/restic/epel-7-$basearch/
    skip_if_unavailable: True
    gpgcheck: 1
    gpgkey: https://download.copr.fedorainfracloud.org/results/copart/restic/pubkey.gpg
    repo_gpgcheck: no
    enabled: yes

- name: Restic - Install
  yum:
    name: restic
    enablerepo: copart-restic
    state: present
