
# install path
apps_name: 'apps'
apps_install_path: '/opt/{{ apps_name }}'


# The password of the repository manager
# from where the jar can be downloaded
# deprecated
# Download info (snapshot latest)
apps_repository_url: http://127.0.0.1:8082/repository/maven-snapshots
apps_repository_user: admin
apps_repository_pwd: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65633361396165313764633934356533373032306161303566666466326233323036323139376664
  3738666238663039333463616632333134353963396633340a363036316266626639306430333630
  61313161366332393065366431356261356666663737656138386363666134356333383936643835
  3838316535383264330a363132616666663664396137323430396634343263666462326135373136
  36353562613033356138343137633962356132373534323565636665656139363966

# Auth
# User password
# user that will run the jar
apps_user_name: '{{ apps_name }}'
apps_user_group: '{{ apps_name }}'
apps_user_pwd: '{{ apps_user_pwd_vault }}'
apps_user_pwd_vault: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35313462656234333235363538646235306338386237623663383530323662333963666363336235
  3738383166353533626262303337313939343035316662370a343035323061656137623436616263
  65343564303335633965653237303061386437326634313962616432393433383334376663333930
  3635373465393338630a626230653166376631323033303334666435313234383330373963666664
  37656635396262623139353937623931623562653062616236326532343265323661
