# App to receive email

inbox_app_name: 'inbox'
inbox_app_domain: '{{inbox_app_name}}.eraldy.com'

inbox_home: '{{ apps_install_path }}/{{ inbox_app_name }}'

inbox_cache_dir: '{{ inbox_home }}/cache'
inbox_fat_jar_path: '{{ inbox_home }}/bytle-smtp-server-all.jar'
