tower_app_name: 'tower'

tower_install_path: '{{ apps_install_path }}/{{ tower_app_name }}'
tower_cache_dir: '{{ tower_install_path }}/cache'
tower_fat_jar_path: '{{ tower_install_path }}/tower-all.jar'

# the alias name should be unique and uppercase
tower_service_name: '{{ tower_app_name |upper }}_SERVICE'

# port
tower_port: 8083

# tower domain
eraldy_api_fqdn: api.eraldy.com



