tower_app_name: 'tower'

tower_install_path: '{{ apps_install_path }}/{{ tower_app_name }}'
tower_cache_dir: '{{ tower_install_path }}/cache'
tower_fat_jar_path: '{{ tower_install_path }}/tower-all.jar'

# the alias name should be unique and uppercase
tower_service_name: '{{ tower_app_name |upper }}_SERVICE'

# port
tower_port: 8083

# tower domain
combo_api_fqdn: api.combostrap.com
combo_analytics_fqdn: analytics.combostrap.com
combo_tower_fqdn: tower.combostrap.com

# tower configuration

tower_conf_secret_url_data_encryption: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32336661313164323266616663393237393931386432623265613933633736396539633536386531
  6137386630633163376261346434643435333063353733630a663136393066646333373766643961
  65626137306538663233663137356437393233633439376535646465356362393536353638373138
  6138353961323839370a306232343831323363613437323138656561623736653362623635343861
  36376564386364666161373664666463636461363061396132663530366265323130376535393066
  35313136386132326665646537343665386164343431373662353761376165643833323930666537
  64323435306563396163633964343430313864333965376230353863373037613135636630663462
  32303133343138343036

tower_conf_dkim_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35373335643064633937393865346235383234393338366166626238393237363662343133396336
  6235653336313864333839303931643335373836343634320a333934306565343864323635376238
  33666331653733393966386336396463343233653330613736343863656364633833643361323266
  6364353134653432350a666265316531626461343766633434366263663163306634316235306337
  31613638353761653761333238646462313534303434313735656365346630366666666433373131
  30343836623463383835336166666565376563326530323061336239306434373436343763643930
  36336436356266393532353465323139353737336531356339616337326430386235383433653361
  36666338663062666364373731653166393334313161393233616335323033323463646363636539
  35313561366630346336373231383437663335366566353235346339653838313065316165333263
  65623261313865613230393139386138303939633039303230306161373262626636333931376231
  35386231303665303564306635633164356366616365363838346638656364633434663734326465
  64336633656632613163653030333831313837666431616532386165376436326437343732336530
  34653939383738666139306239326566663637356232336132373839353536363533393431373039
  65313563636265623365306431613461363637346331353866373737646331376236366238303939
  63353565383635353035363764343962316434643261366565386430303132646163616334303733
  65363536623737383464666561346433366631646561333762326661386338636433663039663132
  38643736373333666563333632346431643665653739333938636536623064653734376138313038
  65653962353863626332333665326335646563313732383037643961643339623631383432386433
  38336635333261613132346231646632353031343130313062646261633235626465653062613366
  37366633323166663762636261376461613733373762623738663963393863656234636133623232
  62363366326534653733613966623764303031666165396361346164343337313536343731333130
  64663864613061616261326561336264646562643261363435333233626530653462626239656132
  35373634653534633462323162663734623931363639323336376361373665613961646631313163
  63646638343035366135316432636532383530323963383034326134333139383364353163303532
  39323435646334386138633238353030623536323562373662626431666331353366376565383236
  31303364336465383431653337313561636136326432636231316331636236323361346361666562
  61626366373133643633623139393136646130356566396165623931633965363335353433666637
  31396562616661323431313935306266643664306338663965616339626238383936643964393437
  38343463316530376432616564326537613463616638393439396430623037343739373430326633
  35386561623665326432303836373532613734333466383830336230633839326432626130393262
  32636164376665313362666337326237373632336664663238313963306436653933643232626166
  64343739326237623935313432346439313332303733666638616239633833316131663933376261
  34336465316564326439396163366539616133343032393435626666313133353363313334626532
  32653564386337353563646263613436373063653564366138646634396463633665363831353363
  39376336346561303366626261633031666131303065356432366563306234336133376435363764
  62383035633138343735353637643036323965356133616330323436363732363838353334623535
  62623162313830326336633135383437336337343834623139663465623065343530353261663338
  36336339616138393236316539383336383763363063353661616139303564323335316633376165
  34623433373838353037376437386262333339396333303931343037663461623036656566633862
  32353339363238643635376464336666633661626332346235646161663765633263663063656335
  36653536363066366231383635643737386165363662383966383266663363303434373564623435
  31383636356332643538626435323231356662343765613861333235333063353634613431643738
  63383766656430393834326465383638346239663733356462623738343035316136613561636534
  63613630363538663231653461646465616461663662353039666232646436346631613534643434
  62666336366532303937653834363661323266633132623462376264383965326363326133303638
  34306365613935306466373365326161663835303030333664346238633338353266333764353739
  30343765323066643830653065616666623163363436353566343861666532393336643433313062
  65383838393230363130616361343366343433666232356264343364333166336662343934376165
  6263

# never ever change this value
tower_conf_secret_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64366432313961363238613462643761343265626335643063313231656231383438346163396233
  6363313863373439373566623639363132643362363531630a316466623830383033356534323363
  66633263616132343162313337323665343330336139623033303930383437373266363465393363
  6435343538626431650a303263333034653265393632396532306533333764396338623064306132
  61653962613031363034373834353165393238393039373261336631356664383265626365613632
  61666662376365383732373263643564306332663863656163376331633838366466663438323964
  65363239363433626336363962656430346338333636623535616463313861343939316335376264
  62343533346663363563

tower_conf_secret_symmetric_data_encryption: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32363065656636383135326137383734353566393437393865313861326236623233613936643633
  3830343338626362653732623736663161316538363862310a343066636533336365656635336331
  31383063376362616438333166653730383835623834636638346434633461363563396663323064
  3038643235323731620a646338323130306636346637663730653032373537336466326133653831
  62646633623139643231396161396165333433313836663664373237623265666532613231376330
  36353034373233353737303532303330323033313630663538333364336265633964303961303337
  63303639653933623237653236393734383630636332613232336165383464383135373762373632
  66353930373139303534

tower_conf_superuser_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30636331313737633933343063653833653466313561343639353261303333616536656266386562
  6563613263363233636132356665346563656533343730380a626238316362663632343232353061
  36313064643265393530363935633833383239333035376231363761336361326533663437666262
  6634326464356539310a326130396637303638383764636138653366626138393632353533323065
  33656164666364326662663135306338613133363333356161336162653836616334386164313636
  33613232326439643366323933666661656163623233306231656562323132366562393536373038
  35383135313634353532636466636232363530666336356665333661646439656238346261383761
  63653439633439623336
