---
drill_group: drill
drill_user: drill
drill_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36633463316535366465383034333930383539663139366262616332653834633866303362613633
  6466336133333238373232623338616438323766393838660a303737383635386136333336353030
  64613064643264383738623561666233343235306463663163323331653534373335376138646130
  3739306538613738360a363831643664326333373439313832366636386361343361303762623739
  62623662343362613034656539653238366531643234623730373833623162326330

# opt
drill_opt_dir: '/opt'
# where the server is downloaded and unzipped
drill_server_dir: '{{ drill_opt_dir }}/apache-drill-{{ drill_version }}'
# the symbolic link
drill_home_dir: '{{ drill_opt_dir }}/drill'

drill_web_ui_port: '8047'
drill_nginx_port: '31009'

drill_log_dir: '{{ drill_server_dir }}/log'

# generally in zookeeper but as we are in standalone mode
# by default, the provider are stored at /tmp/drill/sys.storage_plugins
drill_provider_dir: '/var/drill'
drill_java_version: '1.8'

drill_version: '1.20.0'
drill_checksum: 'sha512:f903abdbcb7f270f4f893bd2bd1ecd44343665a1cef71afda78b01ed355780973927dbeb2877d5a78efaf92b72489b68062a08b5f3336d36fc0ed32071400de0'

# security
drill_htpasswd_location: '/opt/drill/conf/htpasswd'
