files:
  supportFiles/ApiVertxSupport.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/net/bytle/tower/eraldy/app/ComboPublicApi/openapi/invoker/ApiVertxSupport.java
